# Generated by Django 6.1.1 on 2026-10-02 05:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cedula_ruc_original', models.CharField(blank=True, max_length=100)),
                ('cedula_ruc_normalizada', models.CharField(blank=True, db_index=True, max_length=100)),
                ('nombres', models.TextField()),
                ('fallecido', models.BooleanField(default=False)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
