# Generated by Django 6.1.1 on 2026-10-02 05:21

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatastroVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=255)),
                ('periodo', models.CharField(max_length=7)),
                ('archivo_origen', models.FileField(upload_to='catastro/%Y/%m/')),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('activo',), name='catastro_una_version_activa')],
            },
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('source_fid', models.CharField(max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=50)),
                ('canton', models.CharField(blank=True, max_length=50)),
                ('parroquia', models.CharField(blank=True, db_index=True, max_length=100)),
                ('zona', models.CharField(blank=True, max_length=50)),
                ('sector', models.CharField(blank=True, max_length=50)),
                ('manzana', models.CharField(blank=True, max_length=50)),
                ('predio', models.CharField(blank=True, max_length=50)),
                ('barrio', models.TextField(blank=True)),
                ('direccion', models.TextField(blank=True)),
                ('clave_ante', models.CharField(blank=True, db_index=True, max_length=254)),
                ('clave_nuev', models.CharField(blank=True, db_index=True, max_length=254)),
                ('predio_mun', models.CharField(blank=True, db_index=True, max_length=254)),
                ('clave_ag', models.CharField(blank=True, db_index=True, max_length=254)),
                ('cod_client', models.CharField(blank=True, db_index=True, max_length=254)),
                ('nombres_catastro', models.TextField(blank=True)),
                ('ruc_cedula_catastro', models.CharField(blank=True, db_index=True, max_length=254)),
                ('suministro', models.CharField(blank=True, db_index=True, max_length=254)),
                ('total_deud', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('deuda_mese', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('medidor', models.CharField(blank=True, max_length=100)),
                ('atributos_originales', models.JSONField(default=dict)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32717)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catastro.catastroversion')),
            ],
            options={
                'indexes': [models.Index(fields=['version', 'parroquia', 'zona', 'sector'], name='catastro_pr_version_7b9967_idx')],
                'constraints': [models.UniqueConstraint(fields=('version', 'source_fid'), name='predio_version_fid')],
            },
        ),
    ]
