# Generated by Django 6.1.1 on 2026-10-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predio',
            name='geometria_valida',
            field=models.BooleanField(default=True),
        ),
    ]
