# Generated by Django 6.1.1 on 2026-10-02 05:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catastro', '0001_initial'),
        ('clientes', '0001_initial'),
        ('expedientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionCartera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('periodo', models.CharField(max_length=7)),
                ('hoja', models.CharField(default='Sheet 1', max_length=255)),
                ('archivo_original', models.FileField(upload_to='carteras/%Y/%m/')),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('estado', models.CharField(db_index=True, default='PENDIENTE', max_length=40)),
                ('total_filas', models.PositiveIntegerField(default=0)),
                ('filas_validas', models.PositiveIntegerField(default=0)),
                ('filas_revision', models.PositiveIntegerField(default=0)),
                ('filas_error', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('aprobada', models.BooleanField(default=False)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('catastro_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catastro.catastroversion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroCarteraRaw',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('numero_fila', models.PositiveIntegerField()),
                ('datos_originales', models.JSONField()),
                ('importacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw', to='financiera.importacioncartera')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCarteraStaging',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ciu', models.CharField(blank=True, db_index=True, max_length=100)),
                ('cedula_ruc', models.CharField(blank=True, db_index=True, max_length=100)),
                ('nombres', models.TextField(blank=True)),
                ('clave', models.CharField(blank=True, db_index=True, max_length=254)),
                ('predio_mun', models.CharField(blank=True, max_length=254)),
                ('suministro', models.CharField(blank=True, db_index=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('parroquia', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=254)),
                ('correo', models.CharField(blank=True, max_length=254)),
                ('total_emision', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_interes', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_coactiva', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_recargo', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('meses_deuda', models.PositiveIntegerField(default=0)),
                ('fallecido', models.BooleanField(default=False)),
                ('estado_validacion', models.CharField(db_index=True, default='VALIDO', max_length=30)),
                ('estado_catastro', models.CharField(db_index=True, default='SIN_COINCIDENCIA', max_length=30)),
                ('estado_historico', models.CharField(db_index=True, default='NUEVO', max_length=30)),
                ('requiere_revision', models.BooleanField(db_index=True, default=False)),
                ('motivo_revision', models.TextField(blank=True)),
                ('candidatos_catastro', models.JSONField(default=list)),
                ('decision', models.CharField(blank=True, max_length=30)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('predio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catastro.predio')),
                ('proceso_coincidente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='expedientes.expediente')),
                ('raw', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='staging', to='financiera.registrocarteraraw')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarteraDetalle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ciu', models.CharField(blank=True, db_index=True, max_length=100)),
                ('suministro', models.CharField(blank=True, max_length=254)),
                ('clave', models.CharField(blank=True, max_length=254)),
                ('total_emision', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_interes', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_coactiva', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_recargo', models.DecimalField(decimal_places=2, max_digits=18)),
                ('meses_deuda', models.PositiveIntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('predio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catastro.predio')),
                ('importacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financiera.importacioncartera')),
                ('staging', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='financiera.registrocarterastaging')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='registrocarteraraw',
            constraint=models.UniqueConstraint(fields=('importacion', 'numero_fila'), name='raw_fila_unica'),
        ),
    ]
