# Generated by Django 6.1.1 on 2026-10-02 05:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('numero_negocio', models.CharField(blank=True, max_length=100, null=True)),
                ('parroquia', models.CharField(max_length=100)),
                ('zona', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('estado', models.CharField(default='ABIERTA', max_length=40)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
