# Generated by Django 6.1.1 on 2026-10-02 05:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ciu', models.CharField(blank=True, db_index=True, max_length=100)),
                ('suministro', models.CharField(blank=True, db_index=True, max_length=254)),
                ('clave', models.CharField(blank=True, db_index=True, max_length=254)),
                ('numero_negocio', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(db_index=True, default='PENDIENTE_PRELIMINAR', max_length=40)),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('caso_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
            ],
        ),
    ]
