# Generated by Django 6.1.1 on 2026-10-02 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catastro', '0001_initial'),
        ('expedientes', '0001_initial'),
        ('financiera', '0001_initial'),
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='detalle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='financiera.carteradetalle'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='ordenes.orden'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='predio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catastro.predio'),
        ),
        migrations.AddConstraint(
            model_name='expediente',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'CERRADO'), _negated=True), fields=('caso_fingerprint',), name='expediente_caso_activo_unico'),
        ),
    ]
