# Generated by Django 6.1.1 on 2026-10-02 05:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expedientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaRecargo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('configuracion', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Preliminar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='PENDIENTE_CABILDO', max_length=30)),
                ('archivo_pdf', models.FileField(blank=True, upload_to='preliminares/%Y/%m/')),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('cantidad_titulos', models.PositiveIntegerField(blank=True, null=True)),
                ('recargo_reportado', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fuente', models.CharField(default='ERP_CABILDO', editable=False, max_length=30)),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='preliminar', to='expedientes.expediente')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
