# Generated by Django 6.1.1 on 2026-10-02 05:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expedientes', '0001_initial'),
        ('ordenes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteNotificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_programada', models.DateField()),
                ('estado', models.CharField(default='PENDIENTE', max_length=30)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='ordenes.orden')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AsignacionNotificador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='ASIGNADO', max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='asignacion', to='expedientes.expediente')),
                ('usuario_notificador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='notificaciones.lotenotificacion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
