# Generated by Django 6.1.1 on 2026-10-02 05:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(db_index=True, max_length=100)),
                ('entidad', models.CharField(db_index=True, max_length=100)),
                ('id_entidad', models.CharField(db_index=True, max_length=100)),
                ('metadata', models.JSONField(default=dict)),
                ('antes', models.JSONField(default=dict)),
                ('despues', models.JSONField(default=dict)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
